name: tulemar_stack

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      # SSL certificates (existing)
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_webroot:/var/www/certbot:ro
      # Logs
      - nginx_logs:/var/log/nginx
      # Static and media files for direct serving
      - grocery_static:/srv/grocery_static:ro
      - grocery_media:/srv/grocery_media:ro
      - vipsite_static:/srv/vip_static:ro
      - vipsite_media:/srv/vip_media:ro
    networks: [tulemar_net]
    depends_on:
      grocery-web:
        condition: service_healthy
      vipsite-web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  redis-grocery:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --dbfilename grocery.rdb
    volumes:
      - redis_grocery_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [tulemar_net]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-vip:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --dbfilename vip.rdb --port 6380
    volumes:
      - redis_vip_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [tulemar_net]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tulemar_net:
    name: tulemar_net
    driver: bridge

volumes:
  # CRITICAL: These volume names MUST match existing production volumes
  certbot_certs:
    name: certbot_certs
    external: true  # Use existing volume
  certbot_webroot:
    name: certbot_webroot
    external: true  # Use existing volume
  nginx_logs:
    name: nginx_logs
  redis_grocery_data:
    name: redis_grocery_data
  redis_vip_data:
    name: redis_vip_data